import ProjectDescription

let workspace = Workspace(
    name: "Snowman",
    projects: [
        "."
    ],
    generationOptions: Workspace.GenerationOptions.options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
