import ProjectDescription

let workspace = Workspace(
    name: "Snowman",
    projects: [
        "."
    ],
//    schemes: [
//        Scheme(
//            name: "Snowman",
//            buildAction: BuildAction.buildAction(
//                targets: [
//                    TargetReference(stringLiteral: "Snowman")
//                ]
//            ),
//            testAction: TestAction.targets(
//                [
//                    TestableTarget.init(
//                        target: TargetReference(stringLiteral: "SnowmanTests")
//                    ),
//                    TestableTarget.init(
//                        target: TargetReference(stringLiteral: "SnowmanUITests")
//                    )
//                ],
//                options: TestActionOptions.options(
//                    coverage: true,
//                    codeCoverageTargets: [
//                        TargetReference(stringLiteral: "Snowman")
//                    ]
//                )
//            )
//        )
//    ],
    generationOptions: Workspace.GenerationOptions.options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
